In [1]:
import numpy as np

In [2]:
x = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y = np.array([
    [0],[1],[1],[0]
])

print(x,"\n",y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]] 
 [[0]
 [1]
 [1]
 [0]]


In [14]:
# Weight Initialaization

input_to_hidden_bias = 1
hidden_to_output_bias = 1
input_size = 2
hidden_size = 2
output_size = 1

input_to_hidden_weight = np.array([
    [0.6,0.3],
    []
])
hidden_to_output_weight = np.random.rand(hidden_size,output_size)
print(input_to_hidden_weight)
print(hidden_to_output_weight)

[[0.30026426 0.41209678]
 [0.13390676 0.25624268]]
[[0.59129117]
 [0.42774277]]


In [13]:
def forward(x):
    pass

In [19]:
hidden_net_ouput = []

for j in range(hidden_size):
    for i in range(input_size):
        pass