In [1]:
import numpy as np
from matplotlib import pyplot as plt

from sklearn.datasets import make_blobs

In [2]:
X = np.array([
    [-1,-1],
    [-1,1],
    [1,-1],
    [1,1]
])

print(X.shape)

y = np.array([-1,1,1,1])

b = 0.5

(4, 2)


In [14]:
x = np.array([[]])
for i in X:
    kernal = np.power((np.dot(i.reshape(1,-1),X.T)+1),2)
    x = np.concatenate((x,kernal),axis=1)

1
[[9. 1. 1. 1. 1. 9. 1. 1. 1. 1. 9. 1. 1. 1. 1. 9.]]


In [4]:
B = np.dot(b,y.reshape(-1,1))
print(B)

B.shape

[[-0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]


(4, 1)

In [5]:
x_inv = np.linalg.inv(x.reshape(-1,len(X)))
print(x_inv)
x_inv.shape

[[ 0.11458333 -0.01041667 -0.01041667 -0.01041667]
 [-0.01041667  0.11458333 -0.01041667 -0.01041667]
 [-0.01041667 -0.01041667  0.11458333 -0.01041667]
 [-0.01041667 -0.01041667 -0.01041667  0.11458333]]


(4, 4)

In [6]:
W = np.dot(x_inv,B)
print(W)
W.shape

[[-0.07291667]
 [ 0.05208333]
 [ 0.05208333]
 [ 0.05208333]]


(4, 1)

In [16]:
def prediction(X):
    return np.dot(W.T , x.reshape(-1,len(X))).reshape(-1,1)+B

In [17]:
line = prediction(X)

correct = 0
wrong = 0

for i in range(len(line)):
    if line[i] < 0:
        line[i] = -1
    else:
        line[i] = 1

    if line[i] == y[i]:
        correct += 1
    else:
        wrong += 1

print(f"Accuracy:{correct/len(X)*100:.2f}%")

Accuracy:100.00%
