In [2]:
import numpy as np #Numpy Package

In [8]:
x = np.array(([2,9],[1,5],[3,6]),dtype=float)
#np.array() method returns a n-dimensional array
#dtype is the desired data-type for the array
#Here,the data type of the array is float; size = 3x2
y = np.array(([92],[86],[89]),dtype=float)
#size : 3X1
print(x)
print(y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]


In [9]:
x = x/np.amax(x,axis=0) 
#Maximun of X array
#X is input data
#so,np.amax(x,axis=0) gives result as [3. 9.] from 1st and 2nd column respectively
y = y/100 
#max test score is 100
print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [13]:
class Neural_Network(object):
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize,self.hiddenSize)
        print("w1",self.W1)
        self.W2 = np.random.randn(self.hiddenSize,self.outputSize)
        print("w1",self.W1)

    def forward(self,x):
        self.z1 = np.dot(x,self.W1)
        self.z2 = self.sigmoid(self.z1)
        self.z3 = np.dot(self.z2,self.W2)
        output = self.sigmoid(self.z3)
        return output
    
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self,s):
        return s*(1-s)
    
    def backward(self,x,y,output):
        self.output_error = y - output
        self.output_delta = self.output_error * self.sigmoidPrime(output)
        self.z2_error = self.output_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += x.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.output_delta)

    def train(self,x,y):
        Output = self.forward(x)
        self.backward(x,y,Output)

In [14]:
NN = Neural_Network()

w1 [[-1.41376114 -1.40331075 -2.05816378]
 [ 0.52809804  1.03858362  0.45190893]]
w1 [[-1.41376114 -1.40331075 -2.05816378]
 [ 0.52809804  1.03858362  0.45190893]]


In [19]:
for i in range(1000):
    print(f"Data in epoch {i}")
    print("Input : "+str(x))
    print("Actual Output : "+str(y))
    print("Predicted Output : "+str(NN.forward(x)))
    print("Loss : "+str(np.mean(np.square(y - NN.forward(x)))))
    print("\n")
    #Training The Model
    NN.train(x,y)

Data in epoch 0
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.9090657 ]
 [0.87149302]
 [0.88756096]]
Loss : 8.58657826934506e-05


Data in epoch 1
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.90906551]
 [0.87148846]
 [0.88756565]]
Loss : 8.582466295271732e-05


Data in epoch 2
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.90906532]
 [0.87148391]
 [0.88757033]]
Loss : 8.578360027401066e-05


Data in epoch 3
Input : [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output : [[0.92]
 [0.86]
 [0.89]]
Predicted Output : [[0.90906513]
 [0.87147937]
 [0.887575  ]]
Loss : 8.574259455555048e-05


Data in epoch 4
Input : [[0.66666667 1.        ]
 [0.33333333 0.5